### ISSUE TITLE
This notebooks is not pushed to github

### ISSUE THREAD

**Issue by sunnyosun** [laminlabs/arrayloader-benchmarks#12]
@Koncopd you seem to forget to push this notebook:

<img width="1287" alt="Screenshot 2024-03-20 at 09 35 47" src="https://github.com/laminlabs/arrayloader-benchmarks/assets/38218185/8eb147bf-7b3f-435f-98d5-c635f4bd3715">

**Comment by Koncopd** [comment]
Yep, thx, will do.
